name: Release
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    
    env:
      Configuration: Release
      Solution_Name: WordFurigana.sln
      Project_Name: WordFurigana

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=${{ env.Configuration }}

    - name: Install pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.CERTIFICATE }}")
        [IO.File]::WriteAllBytes("key.pfx", $pfx_cert_byte)
        Import-PfxCertificate -FilePath "key.pfx" -CertStoreLocation "Cert:\CurrentUser\My" -Password (ConvertTo-SecureString -String "${{ secrets.CERTIFICATE_PASS }}" -AsPlainText -Force)

    - name: Create the app package
      run: |
        msbuild ${{ env.Project_Name }} /target:Publish /p:Configuration=${{ env.Configuration }}
        Move-Item -Path ${{ env.Project_Name }}\bin\${{ env.Configuration }}\app.publish -Destination Installer
        7z a Installer.zip Installer
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Installer.zip