name: Release
on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest
    
    env:
      Configuration: Release
      Solution_Name: WordFurigana.sln
      Project_Name: WordFurigana

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.7.2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration

    - name: Install pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.CERTIFICATE }}")
        [IO.File]::WriteAllBytes("key.pfx", $pfx_cert_byte)
        Import-PfxCertificate -FilePath "key.pfx" -CertStoreLocation "Cert:\CurrentUser\My" -Password (ConvertTo-SecureString -String "${{ secrets.CERTIFICATE_PASS }}" -AsPlainText -Force)

    - name: Create the app package
      run: msbuild $env:Project_Path /target:Publish /p:Configuration=$env:Configuration
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '$env:Project_Path/publish'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
